basket_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from baskets.views import IndexView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^baskets/', include('baskets.urls', namespace='baskets')),
]


urlpatterns += staticfiles_urlpatterns()

baskets/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from baskets.views import BasketListView, BasketDetailView


urlpatterns = [
    url(r'^$', BasketListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', BasketDetailView.as_view(), name='detail'),
]

baskets/models.py
from django.db import models


class Basket(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    picture = models.FileField(upload_to='uploads')
    type = models.CharField(max_length=255)

    def __str__(self):
        return self.title

baskets/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView

from . import models


class IndexView(TemplateView):
    template_name = 'index.html'


class BasketListView(ListView):
    model = models.Basket
    context_object_name = 'baskets'


class BasketDetailView(DetailView):
    model = models.Basket

baskets/templates/baskets/basket_detail.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block title %}Detail{% endblock %}

{% block content %}
    <h1>Detail</h1>
{% endblock %}

baskets/templates/baskets/basket_list.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block title %}List{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row container-fluid">
            {% for basket in baskets %}
                <div class="card col-lg-4 col-md-6 col-sm-8 container-fluid" style="width: 20rem;">
                    <img class="card-img-top" src="http://coloringhub.com/wp-content/uploads/2014/01/basket-fruit.jpg" alt="Card image cap">
                    <div class="card-block">
                        <h4 class="card-title">{{ basket.title }}</h4>
                        <p class="card-text">{{ basket.description }}</p>
                        <a href="#" class="btn btn-primary">Details</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block title %}Baskets by Lila{% endblock %}

{% block content %}
        <div class="row container-fluid">
            <div class="card col-sm-4" style="width: 20rem;">
              <img class="card-img-top" src="http://coloringhub.com/wp-content/uploads/2014/01/basket-fruit.jpg" alt="Card image cap">
              <div class="card-block">
                <h4 class="card-title">Tuna Basket</h4>
                <p class="card-text">Here is where you put your fresh tuna, in this lovely basket, made of natural colors and natural fish.</p>
                <a href="#" class="btn btn-primary">Details</a>
              </div>
            </div>
        </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Pacifico|Yellowtail" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</head>
<body>
    <!--NavBar-->
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">Baskets by Lila</a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'baskets:list' %}">Baskets</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Gallery
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Pine-Needle Baskets</a>
              <a class="dropdown-item" href="#">Small Baskets</a>
              <a class="dropdown-item" href="#">Large Baskets</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    <!--/NavBar-->
    <!--/Jumbotron-->
    <div class="jumbotron jumbotron-fluid header">
        <div class="container">
        <h1 class="display-3">Baskets by Lila</h1>
        <p class="lead">High Quality Handmade Baskets.</p>
        </div>
    </div>
    <!--/Jumbotron-->
    {% block content %}
    {% endblock %}
</body>
</html>